all:
  hosts:
    Routeur:
    Bastion:
  children:
    webservers:
      hosts:
        WebServer:
    dbservers:
      hosts:
        DataBase:
    reverseproxies:
      hosts:
        ReverseProxy:
